### ISSUE TITLE
singularity image does no find worker code

### ISSUE THREAD

**Issue by goord** [omuse-geoscience/omuse#6]
When I follow the steps from https://omuse.readthedocs.io/en/latest/singularity.html#singularity-section without having omuse built locally, I get the error

```
Singularity omuse.img:/opt/omuse/src/omuse/community/dales/example> python bubble.py
Traceback (most recent call last):
  File "bubble.py", line 22, in <module>
    d = Dales(workdir='bubble', channel_type='sockets', number_of_workers=1)
  File "/home/gvdoord/Software/amuse/src/omuse/src/omuse/community/dales/interface.py", line 587, in __init__
    CommonCode.__init__(self, DalesInterface(**options), **options)
  File "/home/gvdoord/Software/amuse/src/omuse/src/omuse/community/dales/interface.py", line 34, in __init__
    CodeInterface.__init__(self, name_of_the_worker=self.name_of_the_worker(), **options)
  File "/home/gvdoord/.local/lib/python3.6/site-packages/amuse/rfi/core.py", line 752, in __init__
    self._start(name_of_the_worker = name_of_the_worker, **options)
  File "/home/gvdoord/.local/lib/python3.6/site-packages/amuse/rfi/core.py", line 771, in _start
    self.channel = self.channel_factory(name_of_the_worker, type(self), interpreter_executable = interpreter_executable, **options)
  File "/home/gvdoord/.local/lib/python3.6/site-packages/amuse/rfi/channel.py", line 1694, in __init__
    self.full_name_of_the_worker = self.get_full_name_of_the_worker(legacy_interface_type)
  File "/home/gvdoord/.local/lib/python3.6/site-packages/amuse/rfi/channel.py", line 692, in get_full_name_of_the_worker
    raise exceptions.CodeException("The worker application does not exist, it should be at: \n{0}".format('\n'.join(tried_workers)))
amuse.support.exceptions.CodeException: The worker application does not exist, it should be at: 
/home/gvdoord/Software/amuse/src/omuse/src/omuse/_workers/dales_worker
/home/gvdoord/.local/lib/python3.6/site-packages/amuse/_workers/dales_worker
/home/gvdoord/Software/amuse/src/omuse/src/omuse/community/dales/dales_worker
/home/gvdoord/.local/lib/python3.6/site-packages/amuse/rfi/dales_worker
```
Somehow it tries to find the worker from my home directory, am I missing something?

**Comment by goord** [comment]
Perhaps the installation in the singularity image should be modified such that it does not attempt to find worker codes in the ```.local``` directory which is mounted in the container...

**Comment by fjansson** [comment]
I think the problem is that some python modules in your home directory leak into the container.
This can be prevented by adding `-H <absolute-path>` when launching singularity, this mounts the specified path as the home directory inside the container. I just tested this with an empty directory, and it worked. This should work both for singularity shell and singularity run.

In other words, I think it's about what's mounted when running the container and not while building it. 
Let's add this to the instructions, create empty home dir, launch with... -H that dir.

**Comment by goord** [comment]
Yes that works!
